kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-argocd-cluster-argocd-application-controller-sysflow
rules:
  - verbs:
      - create 
      - get 
      - list
      - patch
    apiGroups: 
      - security.openshift.io
    resources: 
      - securitycontextconstraints